webclient/Models/ErrorViewModel.cs
namespace Transcoder.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

webclient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Transcoder.Web.Models;

namespace Transcoder.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

webclient/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging;
using Transcoder.Web.Models;

namespace Transcoder.Web.Controllers
{
    [Route("[controller]")]
    public class VideoController : Controller
    {
        private readonly ILogger<VideoController> _logger;
        private readonly IFileProvider _fileProvider;

        public VideoController(ILogger<VideoController> logger, IFileProvider fileProvider)
        {
            _logger = logger;
            _fileProvider = fileProvider;
        }

        [HttpGet("Index")]
        public IActionResult Index()
        {
            var directories = Directory.GetDirectories("/data");
            var folders = directories.Select(a => Path.GetFileName(a)).ToList();
            return View(folders);
        }

        [HttpGet("Player")]
        public IActionResult Detail(string file)
        {
            _logger.LogInformation("Get request with File = {0}", file);
            string pathFile = Path.Combine("/data", file);
            if (!Directory.Exists(pathFile))
            {
                _logger.LogError("File directory not found. File = {0}", file);
                throw new FileNotFoundException("File not found");
            }
            _logger.LogInformation("Directory found, request with File = {0}", file);
            return View("Detail", file);
        }

        [HttpHead("File"), HttpGet("File")]
        public IActionResult FileAction(string name)
        {
            _logger.LogInformation("Get request with File = {0}", name);

            var fileInfo = _fileProvider.GetFileInfo(name);
            if (fileInfo.Exists)
            {
                _logger.LogInformation("File found, File = {0}", name);

                return File(fileInfo.CreateReadStream(), "application/octet-stream", fileInfo.Name);
            }
            _logger.LogInformation("File not found, File = {0}", name);
            return NotFound();

        }
    }
}

webclient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

webclient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Transcoder.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Transcoder.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Transcoder.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">Video</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Transcoder.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

webclient/Views/Video/Detail.cshtml
@model string

@{
    ViewData["Title"] = "Video Viewer";
}

<div class="text-center">
    <h1 class="display-4">EZDRM with Shaka Player</h1>
    <p>Demo with Shaka Player</p>
</div>

<h2>DRM Protected Video Playback</h2>
    <video id="video" width="640" controls autoplay></video>

    <!-- Include Shaka Player JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.0.0/shaka-player.compiled.js"></script>

    <script>
        async function initPlayer() {
            const video = document.getElementById('video');
            const player = new shaka.Player(video);

            // Error handling
            player.addEventListener('error', (e) => {
                console.error('Error code', e.detail.code, 'object', e.detail);
            });

            // Configure DRM license server URLs
            player.configure({
                drm: {
                    servers: {
                        'com.widevine.alpha': 'https://widevine-dash.ezdrm.com/widevine-php/widevine-foreignkey.php?pX=E503E1',
                        'com.microsoft.playready': 'https://playready.ezdrm.com/cency/preauth.aspx?pX=E503E1'
                    },

                    @* clearKeys: {
                        '43feb387fb6e44edb9dc67fb6dbfaabb': '0a9ca9cf0d7199dc844c0a786390aed5'
                    } *@
                }
            });

            // Load the encrypted DASH video
            try {
                await player.load('@Url.Action("file", "video")?name=@Model/h264.mpd');  // Local path to your DASH manifest
                console.log('The video has successfully loaded.');
            } catch (e) {
                console.error('Error loading video', e);
            }
        }

        document.addEventListener('DOMContentLoaded', initPlayer);
 </script>

webclient/Views/Video/Index.cshtml
@model IEnumerable<string>

@{
    ViewData["Title"] = "Video List";
}

<div class="text-center">
    <h1 class="display-4">Video List</h1>
    <ul>
    @foreach(var item in Model)
    {
        <li><a href="@Url.Action("player", "video", new {file = @item})">@item</a></li>
    }
    </ul>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>